/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PJViewController;
import dao.CTHoaDon_dao;
import dao.HoaDon_dao;
import dao.KhanhHang_dao;
import dao.NhanVien_dao;
import dao.SanPham_dao;
import dao.User_dao;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modal.CTHoaDon;
import modal.GeneratorID;
import modal.HoaDon;
import modal.KhanhHang;
import modal.NhanVien;
import modal.QLSpham;
import modal.SanPham;

/**
 *
 * @author HELLO
 */
public class PJView extends javax.swing.JFrame {
    private QLSpham qLSpham;
    private static int currentIndex = 0;
    
    
    /**
     * Creates new form PJView
     */
    public PJView() {
        this.qLSpham = new QLSpham();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        fillTablePro();
        fillSaleTable();
        fillBillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTP_products = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPn_products = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTb_dssp = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTF_timsp = new javax.swing.JTextField();
        jBtn_timsp = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jBtn_prev = new javax.swing.JButton();
        jBtn_next = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLb_ct_picture = new javax.swing.JLabel();
        jLb_ct_tensp = new javax.swing.JLabel();
        jLb_ct_dvt = new javax.swing.JLabel();
        jLb_ct_dongia = new javax.swing.JLabel();
        jBtn_xemct = new javax.swing.JButton();
        jBtn_muahang = new javax.swing.JButton();
        jPn_quanlysp = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTb_quanlysp = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTF_ql_timsp = new javax.swing.JTextField();
        jBtn_ql_timsp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTF_ql_tensp = new javax.swing.JTextField();
        jTF_ql_dvt = new javax.swing.JTextField();
        jTF_ql_dongia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTF_ql_sl = new javax.swing.JTextField();
        jTF_ql_link = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jBtn_ql_them = new javax.swing.JButton();
        jBtn_ql_dongy = new javax.swing.JButton();
        jBtn_ql_sua = new javax.swing.JButton();
        jBtn_ql_capnhat = new javax.swing.JButton();
        jBtn_ql_huy = new javax.swing.JButton();
        jBtn_ql_xoa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLb_pc_tensp = new javax.swing.JLabel();
        jLb_pc_total = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTF_amount = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLb_pc_dongia = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTF_diachi = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTF_tenkh = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTF_sdt = new javax.swing.JTextField();
        jBtn_undo = new javax.swing.JButton();
        jBtn_pay = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLb_time = new javax.swing.JLabel();
        jBtn_check = new javax.swing.JButton();
        jTF_pc_tennv = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTb_bill = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLb_bill_mahd = new javax.swing.JLabel();
        jLb_bill_masp = new javax.swing.JLabel();
        jLb_bill_total = new javax.swing.JLabel();
        jLb_bill_sl = new javax.swing.JLabel();
        jBtn_xembill = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMn_save = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMn_open = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý bán hàng");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTP_products.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTP_products.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTP_products.setPreferredSize(new java.awt.Dimension(1162, 600));

        jPanel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jTP_products.addTab("tab1", jPanel1);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Sản phẩm hiện có");
        jLabel1.setPreferredSize(new java.awt.Dimension(116, 17));

        jTb_dssp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTb_dssp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Đơn vị tính", "Đơn giá", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(jTb_dssp);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Tìm sản phẩm");

        jTF_timsp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jBtn_timsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-icon.png"))); // NOI18N
        jBtn_timsp.setText("Tìm");
        jBtn_timsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_timspActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jBtn_prev.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Previous-icon.png"))); // NOI18N
        jBtn_prev.setText("Trước đó");
        jBtn_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_prevActionPerformed(evt);
            }
        });

        jBtn_next.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Next-icon.png"))); // NOI18N
        jBtn_next.setText("Tiếp");
        jBtn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_nextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Tên sản phẩm:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Đơn vị tính:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Đơn giá:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Thông tin chi tiết sản phẩm");

        jLb_ct_picture.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLb_ct_picture.setForeground(new java.awt.Color(0, 0, 0));
        jLb_ct_picture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_ct_picture.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jLb_ct_picture.setOpaque(true);

        jLb_ct_tensp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLb_ct_tensp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLb_ct_dvt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLb_ct_dvt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLb_ct_dongia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLb_ct_dongia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jBtn_xemct.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_xemct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Programming-Show-Property-icon.png"))); // NOI18N
        jBtn_xemct.setText("Xem chi tiết");
        jBtn_xemct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_xemctActionPerformed(evt);
            }
        });

        jBtn_muahang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_muahang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Finance-Purchase-Order-icon.png"))); // NOI18N
        jBtn_muahang.setText("Mua hàng");
        jBtn_muahang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_muahangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jBtn_prev, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLb_ct_tensp, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_ct_dvt, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_ct_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jLb_ct_picture, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBtn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtn_xemct, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtn_muahang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLb_ct_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLb_ct_tensp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jBtn_xemct, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBtn_prev, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLb_ct_dvt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(jBtn_muahang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLb_ct_picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPn_productsLayout = new javax.swing.GroupLayout(jPn_products);
        jPn_products.setLayout(jPn_productsLayout);
        jPn_productsLayout.setHorizontalGroup(
            jPn_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPn_productsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPn_productsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTF_timsp, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtn_timsp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(jPn_productsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPn_productsLayout.setVerticalGroup(
            jPn_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPn_productsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPn_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_timsp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_timsp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTP_products.addTab("Sản phẩm", new javax.swing.ImageIcon(getClass().getResource("/image/Data-List-icon.png")), jPn_products); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Quản lý sản phẩm");

        jTb_quanlysp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTb_quanlysp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Đơn vị tính", "Đơn giá", "Số lượng", "Link hình ảnh"
            }
        ));
        jScrollPane2.setViewportView(jTb_quanlysp);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Tìm sản phẩm");

        jTF_ql_timsp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTF_ql_timsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_ql_timspActionPerformed(evt);
            }
        });

        jBtn_ql_timsp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_ql_timsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-icon.png"))); // NOI18N
        jBtn_ql_timsp.setText("Tìm ");
        jBtn_ql_timsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ql_timspActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Tên sản phẩm");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Đơn vị tính");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Đơn giá");

        jTF_ql_tensp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTF_ql_dvt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTF_ql_dongia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Số lượng");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Link hình ảnh");

        jTF_ql_sl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTF_ql_link.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_ql_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTF_ql_dvt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTF_ql_tensp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_ql_sl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_ql_link, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_ql_tensp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_ql_sl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_ql_dvt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_ql_link, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_ql_dongia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jBtn_ql_them.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_ql_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Add-icon.png"))); // NOI18N
        jBtn_ql_them.setText("Thêm");
        jBtn_ql_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ql_themActionPerformed(evt);
            }
        });

        jBtn_ql_dongy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_ql_dongy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ok-icon.png"))); // NOI18N
        jBtn_ql_dongy.setText("OK");
        jBtn_ql_dongy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ql_dongyActionPerformed(evt);
            }
        });

        jBtn_ql_sua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_ql_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Gear-icon.png"))); // NOI18N
        jBtn_ql_sua.setText("Sửa");
        jBtn_ql_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ql_suaActionPerformed(evt);
            }
        });

        jBtn_ql_capnhat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_ql_capnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-document-edit-icon.png"))); // NOI18N
        jBtn_ql_capnhat.setText("Cập nhật");
        jBtn_ql_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ql_capnhatActionPerformed(evt);
            }
        });

        jBtn_ql_huy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_ql_huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Delete-icon.png"))); // NOI18N
        jBtn_ql_huy.setText("Hủy");
        jBtn_ql_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ql_huyActionPerformed(evt);
            }
        });

        jBtn_ql_xoa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_ql_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Close-icon.png"))); // NOI18N
        jBtn_ql_xoa.setText("Xóa");
        jBtn_ql_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ql_xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jBtn_ql_them, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtn_ql_dongy, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jBtn_ql_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_ql_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jBtn_ql_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_ql_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_ql_them, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_ql_dongy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_ql_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_ql_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_ql_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_ql_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPn_quanlyspLayout = new javax.swing.GroupLayout(jPn_quanlysp);
        jPn_quanlysp.setLayout(jPn_quanlyspLayout);
        jPn_quanlyspLayout.setHorizontalGroup(
            jPn_quanlyspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPn_quanlyspLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPn_quanlyspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPn_quanlyspLayout.createSequentialGroup()
                        .addGroup(jPn_quanlyspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPn_quanlyspLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel9)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jTF_ql_timsp, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(jPn_quanlyspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPn_quanlyspLayout.createSequentialGroup()
                                .addComponent(jBtn_ql_timsp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)))))
                .addContainerGap())
        );
        jPn_quanlyspLayout.setVerticalGroup(
            jPn_quanlyspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPn_quanlyspLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPn_quanlyspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_ql_timsp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_ql_timsp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPn_quanlyspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTP_products.addTab("Quản lý kho", new javax.swing.ImageIcon(getClass().getResource("/image/Address-Book-2-icon.png")), jPn_quanlysp); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Tên sản phẩm:");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Đơn giá:");

        jLb_pc_tensp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLb_pc_tensp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLb_pc_total.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLb_pc_total.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Số lượng mua:");

        jTF_amount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Thành tiền:");

        jLb_pc_dongia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLb_pc_dongia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Tên nhân viên:");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Tên khách hàng:");

        jTF_diachi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTF_diachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_diachiActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Địa chỉ:");

        jTF_tenkh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Số điện thoại:");

        jTF_sdt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTF_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_sdtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 115, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTF_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jBtn_undo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_undo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Very-Basic-Undo-icon.png"))); // NOI18N
        jBtn_undo.setText("Hoàn tác");
        jBtn_undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_undoActionPerformed(evt);
            }
        });

        jBtn_pay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Car-Coins-icon.png"))); // NOI18N
        jBtn_pay.setText("Thanh toán");
        jBtn_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_payActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Ngày lập:");

        jLb_time.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLb_time.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jBtn_check.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Very-Basic-Checkmark-icon.png"))); // NOI18N
        jBtn_check.setText("Check");
        jBtn_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_checkActionPerformed(evt);
            }
        });

        jTF_pc_tennv.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLb_pc_tensp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTF_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLb_pc_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLb_pc_total, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_pc_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtn_undo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_check, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLb_pc_tensp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLb_pc_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTF_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_pc_total, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_pc_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jBtn_check, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_undo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jBtn_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTP_products.addTab("Mua hàng", new javax.swing.ImageIcon(getClass().getResource("/image/Ecommerce-Return-Purchase-icon.png")), jPanel4); // NOI18N

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Lịch sử mua hàng");

        jTb_bill.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTb_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã khách hàng", "Mã nhân viên", "Ngày lập"
            }
        ));
        jScrollPane3.setViewportView(jTb_bill);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("jLabel28");

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("Mã hóa đơn:");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Số lượng mua:");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("Tổng tiền:");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText("Mã sản phẩm:");

        jLb_bill_mahd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLb_bill_mahd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLb_bill_masp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLb_bill_masp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLb_bill_total.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLb_bill_total.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLb_bill_sl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLb_bill_sl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jBtn_xembill.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_xembill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Programming-Show-Property-icon.png"))); // NOI18N
        jBtn_xembill.setText("Xem chi tiết");
        jBtn_xembill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_xembillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLb_bill_mahd, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLb_bill_sl, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLb_bill_total, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLb_bill_masp, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtn_xembill, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_bill_mahd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_bill_masp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jBtn_xembill, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_bill_sl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_bill_total, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTP_products.addTab("Hóa đơn", new javax.swing.ImageIcon(getClass().getResource("/image/Ecommerce-Bill-icon.png")), jPanel10); // NOI18N

        getContentPane().add(jTP_products, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jMn_save.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMn_save.setText("Save");
        jMenu1.add(jMn_save);
        jMenu1.add(jSeparator1);

        jMn_open.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMn_open.setText("Open");
        jMenu1.add(jMn_open);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_ql_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ql_xoaActionPerformed
        // Remove a product on table and database
        delProduct();
    }//GEN-LAST:event_jBtn_ql_xoaActionPerformed

    private void jBtn_ql_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ql_huyActionPerformed
        clearProData();
    }//GEN-LAST:event_jBtn_ql_huyActionPerformed

    private void jBtn_ql_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ql_capnhatActionPerformed
        // Update product information
        updateProduct();
    }//GEN-LAST:event_jBtn_ql_capnhatActionPerformed

    private void jBtn_ql_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ql_suaActionPerformed
        // Show selected product infor
        showSelectedPro();
    }//GEN-LAST:event_jBtn_ql_suaActionPerformed

    private void jBtn_ql_dongyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ql_dongyActionPerformed
        // Add product on table and database
        addProduct();
    }//GEN-LAST:event_jBtn_ql_dongyActionPerformed

    private void jBtn_ql_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ql_themActionPerformed
        // Clear product in input form
        clearProData();
    }//GEN-LAST:event_jBtn_ql_themActionPerformed

    private void jBtn_ql_timspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ql_timspActionPerformed
        // Reload before finding
        fillTablePro();

        // Find product by name
        findProByName(this.jTF_ql_timsp, this.jTb_quanlysp);
    }//GEN-LAST:event_jBtn_ql_timspActionPerformed

    private void jTF_ql_timspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_ql_timspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_ql_timspActionPerformed

    private void jBtn_muahangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_muahangActionPerformed
        // start purchase
        purchaseClick();
        
        this.jTP_products.setSelectedComponent(this.jPanel4);
    }//GEN-LAST:event_jBtn_muahangActionPerformed

    private void jBtn_xemctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_xemctActionPerformed
        // See details product
        seeDetails();
        
        fillTablePro();
        fillSaleTable();
    }//GEN-LAST:event_jBtn_xemctActionPerformed

    private void jBtn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_nextActionPerformed
        ArrayList<SanPham> listSP = SanPham_dao.getInstance().selectAll();
        if(currentIndex != listSP.size() - 1) {
            currentIndex++;
        }
        getProInforFromDB(currentIndex);
    }//GEN-LAST:event_jBtn_nextActionPerformed

    private void jBtn_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_prevActionPerformed
        ArrayList<SanPham> listSP = SanPham_dao.getInstance().selectAll();
        if(currentIndex != 0) {
            currentIndex--;
        }
        getProInforFromDB(currentIndex);
    }//GEN-LAST:event_jBtn_prevActionPerformed

    private void jBtn_timspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_timspActionPerformed
        // Reload before finding
        fillSaleTable();

        // Find product by name
        findProByName(this.jTF_timsp, this.jTb_dssp);
    }//GEN-LAST:event_jBtn_timspActionPerformed

    private void jTF_diachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_diachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_diachiActionPerformed

    private void jTF_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_sdtActionPerformed

    private void jBtn_undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_undoActionPerformed
        // Undo purchase
        undoPurchase();
    }//GEN-LAST:event_jBtn_undoActionPerformed

    private void jBtn_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_checkActionPerformed
        // Check price
        checkPrice();
    }//GEN-LAST:event_jBtn_checkActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LoginFormPJ loginForm = new LoginFormPJ();
        loginForm.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void jBtn_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_payActionPerformed
        // Compelte purchase
        completePurchase();
        
        // Check complete purchase
        checkCompletePurchase();
        
        
        fillTablePro();
        fillSaleTable();
        fillBillTable();
    }//GEN-LAST:event_jBtn_payActionPerformed

    private void jBtn_xembillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_xembillActionPerformed
        // See details bill
        seeDetailsBillTable();
    }//GEN-LAST:event_jBtn_xembillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PJView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PJView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PJView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PJView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PJView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_check;
    private javax.swing.JButton jBtn_muahang;
    private javax.swing.JButton jBtn_next;
    private javax.swing.JButton jBtn_pay;
    private javax.swing.JButton jBtn_prev;
    private javax.swing.JButton jBtn_ql_capnhat;
    private javax.swing.JButton jBtn_ql_dongy;
    private javax.swing.JButton jBtn_ql_huy;
    private javax.swing.JButton jBtn_ql_sua;
    private javax.swing.JButton jBtn_ql_them;
    private javax.swing.JButton jBtn_ql_timsp;
    private javax.swing.JButton jBtn_ql_xoa;
    private javax.swing.JButton jBtn_timsp;
    private javax.swing.JButton jBtn_undo;
    private javax.swing.JButton jBtn_xembill;
    private javax.swing.JButton jBtn_xemct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLb_bill_mahd;
    private javax.swing.JLabel jLb_bill_masp;
    private javax.swing.JLabel jLb_bill_sl;
    private javax.swing.JLabel jLb_bill_total;
    private javax.swing.JLabel jLb_ct_dongia;
    private javax.swing.JLabel jLb_ct_dvt;
    private javax.swing.JLabel jLb_ct_picture;
    private javax.swing.JLabel jLb_ct_tensp;
    private javax.swing.JLabel jLb_pc_dongia;
    private javax.swing.JLabel jLb_pc_tensp;
    private javax.swing.JLabel jLb_pc_total;
    private javax.swing.JLabel jLb_time;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMn_open;
    private javax.swing.JMenuItem jMn_save;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPn_products;
    private javax.swing.JPanel jPn_quanlysp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTF_amount;
    private javax.swing.JTextField jTF_diachi;
    private javax.swing.JTextField jTF_pc_tennv;
    private javax.swing.JTextField jTF_ql_dongia;
    private javax.swing.JTextField jTF_ql_dvt;
    private javax.swing.JTextField jTF_ql_link;
    private javax.swing.JTextField jTF_ql_sl;
    private javax.swing.JTextField jTF_ql_tensp;
    private javax.swing.JTextField jTF_ql_timsp;
    private javax.swing.JTextField jTF_sdt;
    private javax.swing.JTextField jTF_tenkh;
    private javax.swing.JTextField jTF_timsp;
    private javax.swing.JTabbedPane jTP_products;
    private javax.swing.JTable jTb_bill;
    private javax.swing.JTable jTb_dssp;
    private javax.swing.JTable jTb_quanlysp;
    // End of variables declaration//GEN-END:variables

    
    // Clear data from input form(management product)
    public void clearProData() {
        this.jTF_ql_tensp.setText("");
        this.jTF_ql_dvt.setText("");
        this.jTF_ql_dongia.setText("");
        this.jTF_ql_sl.setText("");
        this.jTF_ql_link.setText("");
    }
    
    
    // Get data form input form(management product)
    public SanPham getProData() { 
       String tensp = this.jTF_ql_tensp.getText();
       String dvt = this.jTF_ql_dvt.getText();
       float dongia = Float.valueOf(this.jTF_ql_dongia.getText());
       int sl = Integer.valueOf(this.jTF_ql_sl.getText());
       String url = this.jTF_ql_link.getText();
       
       String masp = GeneratorID.randomAlphaNumeric(6);
       
       SanPham sanPham = new SanPham(masp, tensp, dvt, dongia, sl, url);
        
       return sanPham;
    }
    
    
    // Add bill on table
    public void addBillOnTable(HoaDon hd) {
        DefaultTableModel model = (DefaultTableModel) jTb_bill.getModel();
        model.addRow(new Object[] {
            hd.getMahd(), hd.getKhanhHang().getMakh(), hd.getNhanVien().getManv(), hd.getNgaylap()
	}); 
    }
    
    
    // Add product on table
    public void addProOnTable(SanPham sp) {
        DefaultTableModel model = (DefaultTableModel) jTb_quanlysp.getModel();
	model.addRow(new Object[] {
            sp.getMasp(), sp.getTensp(), sp.getDonvitinh(), sp.getDongia() + "00 VND", sp.getSoluong(), sp.getUrl()
	}); 
    } 
    
    
    // Add product on sale table
    public void adddProOnSaleTable(SanPham sp) {
        DefaultTableModel model = (DefaultTableModel) jTb_dssp.getModel();
	model.addRow(new Object[] {
            sp.getMasp(), sp.getTensp(), sp.getDonvitinh(), sp.getDongia() + "00 VND", sp.getSoluong()
	}); 
    }
    
    
    // Add product
    public void addProduct() {
        SanPham sanPham = getProData();
        this.qLSpham.insert(sanPham);
        SanPham_dao.getInstance().insert(sanPham);
        addProOnTable(sanPham);
        
        clearProData();
    }
    
    
    // Fill table product
    public void fillTablePro() {
        // Remove all on table
        removeAllOnTable(jTb_quanlysp);
        
        ArrayList<SanPham> listSP = SanPham_dao.getInstance().selectAll();
        for (SanPham sanPham : listSP) {
            addProOnTable(sanPham);
        }
    }
    
    
    // Fill bill table
    public void fillBillTable() {
        // Remove all on table
        removeAllOnTable(jTb_bill);
        
        ArrayList<HoaDon> listHD = HoaDon_dao.getInstance().selectAll();
        for (HoaDon hoaDon : listHD) {
            addBillOnTable(hoaDon);
        }
        
    }
    
    
    // Fill sale table 
    public void fillSaleTable() {
        // Remove all on table
        removeAllOnTable(jTb_dssp);
        
        ArrayList<SanPham> listSP = SanPham_dao.getInstance().selectAll();
        for (SanPham sanPham : listSP) {
            adddProOnSaleTable(sanPham);
        }
    }
    
    // Remove all on table(management product)
    public void removeAllOnTable(JTable jTable) {
        while(true) {
            DefaultTableModel model = (DefaultTableModel) jTable.getModel();
            int rowCount = model.getRowCount();
            if(rowCount == 0) {
                break;
            }else {
                try {
                    model.removeRow(0);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }
    
    
    
    // Get selected product
    public SanPham getProduct() {
        DefaultTableModel model = (DefaultTableModel) jTb_quanlysp.getModel();
        int iRow = jTb_quanlysp.getSelectedRow();
        
        String price = model.getValueAt(iRow, 3) + "";
        price.substring(0, 7).trim();
        
        String masp = model.getValueAt(iRow, 0) + "";
        String tensp = model.getValueAt(iRow, 1) + "";
        String dvt = model.getValueAt(iRow, 2) + "";
        float dongia = Float.valueOf(price.substring(0, 7).trim());
        int soluong = Integer.valueOf(model.getValueAt(iRow, 4) + "");
        String url = model.getValueAt(iRow, 5) + "";
        
        SanPham sanPham = new SanPham(masp, tensp, dvt, dongia, soluong, url);
        return sanPham;
    }
    
    
    // Show product infor selected
    public void showSelectedPro() {
        SanPham sanPham = getProduct();
        
        this.jTF_ql_tensp.setText(sanPham.getTensp());
        this.jTF_ql_dvt.setText(sanPham.getDonvitinh());
        this.jTF_ql_dongia.setText(sanPham.getDongia() + "00");
        this.jTF_ql_sl.setText(sanPham.getSoluong() + "");
        this.jTF_ql_link.setText(sanPham.getUrl());
    }
    
    
    // Update product
    public void updateProduct() {
        SanPham sp = getProduct();
        String masp = sp.getMasp();
        
        String tensp = this.jTF_ql_tensp.getText();
        String dvt = this.jTF_ql_dvt.getText();
        float dongia = Float.valueOf(this.jTF_ql_dongia.getText());
        int sl = Integer.valueOf(this.jTF_ql_sl.getText());
        String url = this.jTF_ql_link.getText();
        
        SanPham sanPham = new SanPham(masp, tensp, dvt, dongia, sl, url);
        this.qLSpham.del(sp);
        this.qLSpham.insert(sanPham);
        SanPham_dao.getInstance().update(sanPham);
        
        DefaultTableModel model = (DefaultTableModel) jTb_quanlysp.getModel();
        int rowCount = model.getRowCount();
        for(int i = 0; i < rowCount; i++) {
            String proCode = model.getValueAt(i, 0) + "";
            if(masp.equalsIgnoreCase(proCode)) {
                jTb_quanlysp.setValueAt(masp, i, 0);
                jTb_quanlysp.setValueAt(tensp, i, 1);
                jTb_quanlysp.setValueAt(dvt, i, 2);
                jTb_quanlysp.setValueAt(dongia + "00 VND", i, 3);
                jTb_quanlysp.setValueAt(sl, i, 4);
                jTb_quanlysp.setValueAt(url, i, 5);
            }
        }
        clearProData();
    }
    
    
    // Delete product
    public void delProduct() {
        DefaultTableModel model = (DefaultTableModel) jTb_quanlysp.getModel();
	int iRow = jTb_quanlysp.getSelectedRow();
	int choose = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa sản phẩm này chứ");
	if(choose == JOptionPane.YES_OPTION) {
            SanPham sanPham = getProduct();
            this.qLSpham.del(sanPham);
            SanPham_dao.getInstance().del(sanPham);
            model.removeRow(iRow);
	}
    }
    
    
    // Find product by name(management product and sale product)
    public void findProByName(JTextField jTextField, JTable jTable) {
        String proName = jTextField.getText() + "";
        SanPham sp = new SanPham(); sp.setTensp(proName);
        ArrayList<SanPham> listSP = SanPham_dao.getInstance().selectByNames(sp);
        
        if(listSP.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm có tên " + proName);
        }else {
            removeAllOnTable(jTable);
            if(jTable == this.jTb_dssp) {
                for (SanPham sanPham : listSP) {
                    adddProOnSaleTable(sanPham);
                }
            }else if(jTable == this.jTb_quanlysp) {
                for (SanPham sanPham : listSP) {
                    addProOnTable(sanPham);
                }
            }
        } 
    }
    
    
    // See details product
    public void seeDetails() {
        DefaultTableModel model = (DefaultTableModel) jTb_dssp.getModel();
	int iRow = jTb_dssp.getSelectedRow();
        
        String masp = model.getValueAt(iRow, 0) + "";
        SanPham sanPham = SanPham_dao.getInstance().selectById(masp);
        
        
        this.jLb_ct_tensp.setText(sanPham.getTensp());
        this.jLb_ct_dvt.setText(sanPham.getDonvitinh());
        this.jLb_ct_dongia.setText(sanPham.getDongia() + "00 VND");
        this.jLb_ct_picture.setIcon(new ImageIcon(getClass().getResource(sanPham.getUrl())));
    }
    
    
    // Get products information from database
    public void getProInforFromDB(int currentIndex) {
        ArrayList<SanPham> listSP = SanPham_dao.getInstance().selectAll();
        Map<Object, Integer> mapSP = new HashMap<Object, Integer>();
        int value = 0;
        for (SanPham sanPham : listSP) {
            mapSP.put(sanPham, value);
            value++;
        }
        Set<Object> set = mapSP.keySet();
        
        for (Object object : set) {
            if(mapSP.get(object) == currentIndex) {
                showDetails((SanPham) object);
            }
        } 
    }

    
    // Show details (prev or next)
    public void showDetails(SanPham sanPham) {
        this.jLb_ct_tensp.setText(sanPham.getTensp());
        this.jLb_ct_dvt.setText(sanPham.getDonvitinh());
        this.jLb_ct_dongia.setText(sanPham.getDongia() + "00 VND");
        this.jLb_ct_picture.setIcon(new ImageIcon(getClass().getResource(sanPham.getUrl())));
    }
    
    
    // Undo purchase
    public void undoPurchase() {
        this.jLb_pc_tensp.setText("");
        this.jTF_pc_tennv.setText("");
        this.jLb_pc_dongia.setText("");
        this.jLb_pc_total.setText("");
        this.jTF_amount.setText("");
        this.jTF_tenkh.setText("");
        this.jTF_diachi.setText("");
        this.jTF_sdt.setText("");
        this.jLb_time.setText("");
    }
    
    
    // Get selected product from list products
    public SanPham getSPFromList() {
        DefaultTableModel model = (DefaultTableModel) jTb_dssp.getModel();
	int iRow = jTb_dssp.getSelectedRow();
        
        String masp = model.getValueAt(iRow, 0) + "";
        String tensp = model.getValueAt(iRow, 1) + "";
        String dvt = model.getValueAt(iRow, 2) + "";
        float dongia = Float.valueOf((model.getValueAt(iRow, 3) + "").substring(0, 7).trim());
        int sl = Integer.valueOf(model.getValueAt(iRow, 4) + "");
        
        SanPham sp = new SanPham(masp, tensp, dvt, dongia, sl, "");
        return sp;
    }
    
    
    // Start purchase
    public void purchaseClick() {   
        SanPham sanPham = getSPFromList();
        this.jLb_pc_tensp.setText(sanPham.getTensp());
        this.jLb_pc_dongia.setText(sanPham.getDongia() + "00 VND");
        //this.jLb_pc_tennv.setText(nv.getTennv());
        
        
        Date date = new Date();
        this.jLb_time.setText(date + "");
    }

    
    // Check price
    public void checkPrice() {
        int amount = Integer.valueOf(this.jTF_amount.getText());
        SanPham sp = getSPFromList();
        if(sp.getSoluong() < amount) {
            JOptionPane.showMessageDialog(this, "Số lượng mua phải nhỏ hơn số lượng hiện có!");
        }else {
            this.jLb_pc_total.setText(amount * sp.getDongia() + "00 VND");
        }
    }
    
    
    // Check exist customer
    public KhanhHang checkExistCustomer() {
        String makh = GeneratorID.randomAlphaNumeric(6);
        String tenkh = this.jTF_tenkh.getText();
        String diachi = this.jTF_diachi.getText();
        String sdt = this.jTF_sdt.getText();

        KhanhHang kh = new KhanhHang(makh, tenkh, diachi, sdt);
        KhanhHang khanhHang = null;
        
        if((KhanhHang_dao.getInstance().selectByName(tenkh)) == null) {
            KhanhHang_dao.getInstance().insert(kh);
        }else {
            khanhHang = KhanhHang_dao.getInstance().selectByName(tenkh);
        }
        return khanhHang;
    }
    
    
    // Complete purchase
    public String completePurchase() {
        KhanhHang kh = checkExistCustomer();
        
        String tennv = this.jTF_pc_tennv.getText();
        NhanVien nv = NhanVien_dao.getInstance().selectByName(tennv);
        
        SanPham sp = getSPFromList();
        
        
        int amount = Integer.valueOf(this.jTF_amount.getText());
        float total = Float.valueOf(this.jLb_pc_total.getText().substring(0,7).trim());
        
        String mahd = GeneratorID.randomAlphaNumeric(6);
        
        Date date = new Date();
        String time = (date.getYear() + 1900) + "-" + ("0" + (date.getMonth() + 1)) + "-" + date.getDate();
        
        HoaDon hd = new HoaDon(mahd, kh, nv, time);
        HoaDon_dao.getInstance().insert(hd);
        
        CTHoaDon cthd = new CTHoaDon(hd, sp, amount, total);
        CTHoaDon_dao.getInstance().insert(cthd);
        
        return mahd;
    }
    
    
    // See details bill table
    public void seeDetailsBillTable() {
        DefaultTableModel model = (DefaultTableModel) jTb_bill.getModel();
	int iRow = jTb_bill.getSelectedRow();
        
        String mahd = model.getValueAt(iRow, 0) + "";
        
        CTHoaDon cthd = CTHoaDon_dao.getInstance().selectById(mahd);
        
        this.jLb_bill_mahd.setText(mahd);
        this.jLb_bill_masp.setText(cthd.getSanPham().getMasp());
        this.jLb_bill_sl.setText(cthd.getSoluong() + "");
        this.jLb_bill_total.setText(cthd.getTongtien() + "00 VND");
    }
    
    
    // Check complete purchase  
    public void checkCompletePurchase() {
        CTHoaDon cthd = CTHoaDon_dao.getInstance().selectById(completePurchase());
        if(cthd == null) {
            JOptionPane.showMessageDialog(this, "Oops! something went wrong");
        }else {
            JOptionPane.showMessageDialog(this, "Thanh toán thành công");
        }
    }
}

